### ISSUE TITLE
这里少了一个深响应的测试用例

### ISSUE THREAD

**Issue by abigmiu** [Rye-z/tiny-vue3#2]
https://github.com/Rye-z/tiny-vue3/blob/1d42ac352f51e5435de6492b6404922fa9f88d2e/core/reactivity/__test__/effect.spec.js#L184

**Comment by Rye-z** [comment]
reactive 默认就是 deep 的，而且深响应涉及到多种数据类型的嵌套，这个库其实只实现了主要逻辑，你可以参考 Vue 官方代码里的测试用例，copy 几个自己完善一下哈

**Comment by Rye-z** [comment]
> https://github.com/Rye-z/tiny-vue3/blob/1d42ac352f51e5435de6492b6404922fa9f88d2e/core/reactivity/__test__/effect.spec.js#L184

reactive 默认就是 deep 的，而且深响应涉及到多种数据类型的嵌套，这个库其实只实现了主要逻辑，你可以参考 Vue 官方代码里的测试用例，copy 几个自己完善一下哈
